#!/usr/bin/python

import glob
import os
import sys

# initial checks to see if correct params have been supplied
if len(sys.argv) < 2:
    print('Params error, usage: `%s ~/Documents/folder/`' % os.path.basename(__file__))
    exit()

music_folder = sys.argv[1]
print('Folder: ' + music_folder)

if music_folder[-1:] != '/':
    print('Folder must end with `/`')
    exit()

# doing execfile() on this file will alter the current interpreter's
# environment so you can import libraries in the virtualenv
activate_this_file = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'venv/bin/activate_this.py')
execfile(activate_this_file, dict(__file__=activate_this_file))

# we can now import dependencies loaded from the venv above
from mutagen.id3 import TIT2, TPE1
import mutagen

renamed = 0
files = glob.glob(music_folder + '*.mp3')
print('Files: %s to process' % len(files))

for filename in files:
    file = mutagen.File(filename)

    # initial values
    title = file.tags.getall('TIT2')[0].text[0]
    artist = file.tags.getall('TPE1')[0].text[0]

    # transform values
    if artist.find('feat.') == -1:
        continue
    new_title = title + ' (feat. ' + artist.split('feat.')[1].strip() + ')'
    new_artist = artist.split('feat.')[0].strip()
    print(new_title)
    renamed += 1

    # update file
    file.tags.add(TIT2(text=[new_title]))
    file.tags.add(TPE1(text=[new_artist]))
    file.save()

print('\nRenamed %s files' % renamed)
